name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Required because ubuntu-latest (20.04) is missing Python 2
      # Some dependencies use it https://github.com/actions/virtual-environments/issues/1816
      - name: Set up Python 2.7.18
        uses: actions/setup-python@v2
        with:
          python-version: 2.7.18

      - name: Setup Python 2 pip
        run: |
          curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py, python2 get-pip.py

      - name: Set up Python 3.8.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.8

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Get pipenv venv hashes
        id: hashes
        run: |
          echo "##[set-output name=root;]$(python -c 'import sys; import base64; import hashlib; print(base64.urlsafe_b64encode(hashlib.sha256(sys.argv[-1].encode()).digest()[:6]).decode()[:8])' $(pwd)/Pipfile)"

      - name: Setup root cache
        uses: actions/cache@v2
        id: root-cache
        with:
          path: /home/runner/.local/share/virtualenvs/pangeo-forge-aws-bakery-${{ steps.hashes.outputs.root }}
          key: root-${{ hashFiles('/home/runner/work/pangeo-forge-aws-bakery/pangeo-forge-aws-bakery/Pipfile.lock') }}

      - name: Install root dependencies
        if: steps.root-cache.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Run linting
        run: |
          make lint
